[package]
name = "influxdb-thingsboard-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rumqttc = "0.24"
serde_json = "1.0"
